from django.urls import path
from . import views
urlpatterns = [
    path('edit_enrollment/<int:id>', views.edit_enrollment, name="edit_enrollment"),
    path('edit_kyc/<int:id>', views.edit_kyc, name="edit_kyc"),
    path('edit_address/<int:id>', views.edit_address, name="edit_address"),
    path('edit_personal_information/<int:id>', views.edit_personal_information, name="edit_personal_information"),
    path('edit_reference_details/<int:id>', views.edit_reference_details, name="edit_reference_details"),
    path('edit_product_details/<int:id>', views.edit_product_details, name="edit_product_details"),
    path('edit_bank_details/<int:id>', views.edit_bank_details, name="edit_bank_details"),
    path('edit_emi_scheme/<int:id>', views.edit_emi_scheme, name="edit_emi_scheme "),
    path('edit_product_information/<int:id>', views.edit_product_information, name="edit_product_information"),
    path('', views.home, name="home"),
    path('dealers/', views.dealers, name="dealers"),
    path('create_dealer/', views.create_dealer, name="create_dealer"),
    path('enrollments/', views.enrollments, name="enrollments"),
    path('get_otp/', views.get_otp, name="get_otp"),
    path('check_otp/<int:otp>/<int:mobile_number>', views.check_otp, name="check_otp"),

    path('create_enrollment/<int:mobile_number>', views.create_enrollment, name="create_enrollment"),
    path('create_employee/', views.create_employee, name="create_employee"),
    path('employee_details/<int:id>', views.employee_details, name="employee_details"),
    path('kyc/<int:id>', views.kyc, name="kyc"),
    path('address/<int:id>', views.address, name="address"),
    path('personal_information/<int:id>', views.personal_information, name="personal_information"),
    path('reference_details/<int:id>', views.reference_details, name="reference_details"),
    path('product_details/<int:id>', views.product_details, name="product_details"),
    path('bank_details/<int:id>', views.bank_details, name="bank_details"),
    path('emi_scheme/<int:id>', views.emi_scheme, name="emi_scheme"),
    path('product_information/<int:id>', views.product_information, name="product_information"),
    path('invoice/<int:id>', views.invoice, name="invoice"),

    path('approval/', views.approval, name="approval"),
    path('profit_loss/', views.profit_loss, name="profit_loss"),
    path('employee/', views.employee, name="employee"),
    path('emi/', views.emi, name="emi"),
    path('submit_emi/', views.submit_emi, name="submit_emi"),
    path('messages/', views.messages, name="messages"),
    path('message_details/<int:id>', views.message_details, name="message_details"),
    path('approve/<int:id>', views.approve, name="approve"),
    path('reject/<int:id>', views.reject, name="reject"),
    path('approval_details/<int:id>', views.approval_details, name="approval_details"),
    path('enrollment_details/<int:id>', views.enrollment_details, name="enrollment_details"),
    path('delete_dealer/<int:id>', views.delete_dealer, name="delete_dealer"),
    path('delete_message/<int:id>', views.delete_message, name="delete_message"),
]
